<?php

namespace iTrack\Custom;

class Constants
{
    const ITRACK_USER_ID = 53;

    const UF_CONTACT_POST_CODE = 'UF_CRM_1779754';
    const UF_CONTACT_STAFF_CNT_CODE = 'UF_CRM_1583962129';
    const UF_CONTACT_SENDPULSE_BOOKS_HISTORY_CODE = 'UF_CRM_1592813245';
    const UF_CONTACT_WEBINAR_COMPLETE_CODE = 'UF_CRM_1582222639';

    const UF_DEAL_POST_CODE = 'UF_CRM_1581842452';
    const UF_DEAL_STAFF_CNT_CODE = 'UF_CRM_1583922680';
    const UF_DEAL_WEBINAR_COMPLETE_CNT_CODE = 'UF_CRM_1591020493';
    const UF_DEAL_WEBINAR_NAME_CODE = 'UF_CRM_1582128619';
    const UF_DEAL_WEBINAR_DATE_CODE = 'UF_CRM_1582128645';

    const DEAL_CAT_SEMINAR_PRACTICE_STAGE_NEW = 'C1:PREPARATION';
    const DEAL_CAT_SEMINAR_PRACTICE_STAGE_SEND = 'C1:1';
    const DEAL_CAT_SEMINAR_PRACTICE_STAGE_PAY = 'C1:2';
    const DEAL_CAT_SEMINAR_PRACTICE_STAGE_LOSE = 'C1:LOSE';
    const DEAL_CAT_SEMINAR_PRACTICE_STAGE_WON = 'C1:WON';
    const DEAL_CAT_ONLINE_PRACTICE_STAGE_NEW = 'C3:NEW';
    const DEAL_CAT_ONLINE_PRACTICE_STAGE_SEND = 'C3:2';
    const DEAL_CAT_ONLINE_PRACTICE_STAGE_LOSE = 'C3:LOSE';
    const DEAL_CAT_ONLINE_PRACTICE_STAGE_WON = 'C3:WON';
    const DEAL_CAT_WEBINAR_STAGE_LOSE = 'C50:LOSE';
    const DEAL_CAT_WEBINAR_STAGE_WON = 'C50:WON';
    const DEAL_CAT_BE4MSK_STAGE_NEW = 'C30:PREPARATION';
    const DEAL_CAT_BE4MSK_STAGE_VISITED = 'C30:PREPAYMENT_INVOICE';
    const DEAL_CAT_BE4MSK_STAGE_PAYBE = 'C30:2';
}